### ISSUE TITLE
[CameraScreen] need to save picture in Firebase

### ISSUE THREAD

**Issue by she0930she** [she0930she/TeamScanMe#2]
getting errors when working on save the image on  Firebase

**Comment by kumarlakshya24** [comment]
Working on saving the image in the library and uploading image to firebase

**Comment by kumarlakshya24** [comment]
Image is getting saved directly now, but the UI looks really bad.

> Working on saving the image in the library and uploading image to firebase

**Comment by kumarlakshya24** [comment]
- Changes made to the UI, added an alert to share score results.
