### ISSUE TITLE
[HistoryScreen] dynamically allocate "image" on Firebase

### ISSUE THREAD

**Issue by she0930she** [she0930she/TeamScanMe#6]
We would want to save the image we took in Firebase.
Then retrieve the data from Firebase, render them on [HistoryScreen].
"firebaseUtil.uploadImage()" is probably the function we should look at.

**Comment by kumarlakshya24** [comment]
```
const fetchImage = async() => {
    useEffect(() => {
        storage()
          .ref('/' + 'C7C7BFA4-BEF5-4C11-9F16-36024DFC4475.jpg') //name in storage in firebase console
          .getDownloadURL()
          .then((url) => {
            setImageUrl(url);
          })
          .catch((e) => console.log('Errors while downloading => ', e));
      }, []);
    
    return (
        <Image style={{height: 200, width: 200}} source={{uri: imageUrl}} />
    );
}
```

The problem here is the image is fetched by the name and not by the image metadata, need to figure out to store/rename objects in firebase storage that is easiest to call.

**Comment by kumarlakshya24** [comment]
- We need a data structure, objects can store the info
